export const PITCH_COLORS = { FA: '#e85d26', SL: '#d4a017', CH: '#4a9eff', CU: '#a855f7', FC: '#10b981', SI: '#f43f5e' };

export const STAT_GROUPS = [
  { label: 'Results', keys: ['ERA', 'FIP', 'K%', 'BB%'] },
  { label: 'Expected', keys: ['xERA', 'xFIP', 'SwStr%', 'F-Strike%'] },
  { label: 'Batted Ball', keys: ['GB%', 'Hard%', 'Barrel%', 'HR/FB'] },
];

// ── Pitch type map (pfx keys → display) ──────────────────────────────────────
export const PITCH_MAP = [
  {
    pctKey: 'pfxFA%',
    wKey: 'pfxwFA/C',
    vKey: 'pfxvFA',
    aaKey: 'pfxaaFA',
    spKey: 'pfxspFA',
    label: 'FA',
    name: 'Fastball',
    color: '#e85d26',
  },
  { pctKey: 'pfxSI%', wKey: 'pfxwSI/C', vKey: 'pfxvSI', aaKey: 'pfxaaSI', spKey: 'pfxspSI', label: 'SI', name: 'Sinker', color: '#fb923c' },
  { pctKey: 'pfxSL%', wKey: 'pfxwSL/C', vKey: 'pfxvSL', aaKey: 'pfxaaSL', spKey: 'pfxspSL', label: 'SL', name: 'Slider', color: '#d4a017' },
  { pctKey: 'pfxFC%', wKey: 'pfxwFC/C', vKey: 'pfxvFC', aaKey: 'pfxaaFC', spKey: 'pfxspFC', label: 'FC', name: 'Cutter', color: '#facc15' },
  {
    pctKey: 'pfxCH%',
    wKey: 'pfxwCH/C',
    vKey: 'pfxvCH',
    aaKey: 'pfxaaCH',
    spKey: 'pfxspCH',
    label: 'CH',
    name: 'Changeup',
    color: '#4a9eff',
  },
  {
    pctKey: 'pfxCU%',
    wKey: 'pfxwCU/C',
    vKey: 'pfxvCU',
    aaKey: 'pfxaaCU',
    spKey: 'pfxspCU',
    label: 'CU',
    name: 'Curveball',
    color: '#a855f7',
  },
  {
    pctKey: 'pfxFS%',
    wKey: 'pfxwFS/C',
    vKey: 'pfxvFS',
    aaKey: 'pfxaaFS',
    spKey: 'pfxspFS',
    label: 'FS',
    name: 'Splitter',
    color: '#10b981',
  },
  {
    pctKey: 'pfxKC%',
    wKey: 'pfxwKC/C',
    vKey: 'pfxvKC',
    aaKey: 'pfxaaKC',
    spKey: 'pfxspKC',
    label: 'KC',
    name: 'Knuckle-C',
    color: '#06b6d4',
  },
  {
    pctKey: 'pfxST%',
    wKey: 'pfxwST/C',
    vKey: 'pfxvST',
    aaKey: 'pfxaaST',
    spKey: 'pfxspST',
    label: 'ST',
    name: 'Sweeper',
    color: '#f43f5e',
  },
  {
    pctKey: 'pfxCV%',
    wKey: 'pfxwCV/C',
    vKey: 'pfxvCV',
    aaKey: 'pfxaaCV',
    spKey: 'pfxspCV',
    label: 'CV',
    name: 'Slow Curve',
    color: '#8b5cf6',
  },
];
