import { ClientNflTeam } from './nfl-team.model';

export const NFL_TEAM_MAP: { [key in ClientNflTeam]: string } = {
  [ClientNflTeam.Bye]: 'Bye',
  [ClientNflTeam.FA]: 'FA',
  [ClientNflTeam.ATL]: 'Atl',
  [ClientNflTeam.BUF]: 'Buf',
  [ClientNflTeam.CHI]: 'Chi',
  [ClientNflTeam.CIN]: 'Cin',
  [ClientNflTeam.CLE]: 'Cle',
  [ClientNflTeam.DAL]: 'Dal',
  [ClientNflTeam.DEN]: 'Den',
  [ClientNflTeam.DET]: 'Det',
  [ClientNflTeam.GB]: 'GB',
  [ClientNflTeam.TEN]: 'Ten',
  [ClientNflTeam.IND]: 'Ind',
  [ClientNflTeam.KC]: 'KC',
  [ClientNflTeam.OAK]: 'Oak',
  [ClientNflTeam.LAR]: 'LAR',
  [ClientNflTeam.MIA]: 'Mia',
  [ClientNflTeam.MIN]: 'Min',
  [ClientNflTeam.NE]: 'NE',
  [ClientNflTeam.NO]: 'NO',
  [ClientNflTeam.NYG]: 'NYG',
  [ClientNflTeam.NYJ]: 'NYJ',
  [ClientNflTeam.PHI]: 'Phi',
  [ClientNflTeam.ARI]: 'Ari',
  [ClientNflTeam.PIT]: 'Pit',
  [ClientNflTeam.LAC]: 'LAC',
  [ClientNflTeam.SF]: 'SF',
  [ClientNflTeam.SEA]: 'Sea',
  [ClientNflTeam.TB]: 'TB',
  [ClientNflTeam.WSH]: 'Wsh',
  [ClientNflTeam.CAR]: 'Car',
  [ClientNflTeam.JAX]: 'Jax',
  [ClientNflTeam.BAL]: 'Bal',
  [ClientNflTeam.HOU]: 'Hou',
} as const;
